#!/usr/bin/env bash
# Create a layout for a situation-style test scenario.
# Usage: ./situation_test_cookie-cutter.sh -n BASENAME
#        ./situation_test_cookie-cutter.sh --name BASENAME

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  cat <<'EOF'
Usage: situation_test_cookie-cutter.sh -n testID
       situation_test_cookie-cutter.sh --name testID

  -n, --name   Test ID to use in 'cli<testID>' to name files and directories.
  -h, --help   Show this help.

Creates next to this script:
  cli<testID>.json
  cli<testID>.sh
  cli<testID>.check
  cli<testID>_fakeRunner.sh
  cli<testID>_KB/
  cli<testID>_out_tmpl_0/
  cli<testID>_out_tmpl_1/

File bodies are defined inside this script; directories are created empty.

After running this, you *MUST* do these steps:
1. fill the *_KB (i.e., knowledgebase folder) with the situation.json file/s
   to be tested.
2. fill the *_out_tmpl_* (i.e., output templates) with the set of output files 
   that are expected to be generated by the job.
3. alter the *.json job details file to define the job to be simulated.
4. alter the *.check file to define how to test the outcome of the test.
5. possibly alter the *_fakeRunner.sh script to fake the execution of the job.

Then, you can run the test as './run_tests.sh -c <name>'

EOF
}

NAME=""
while [ $# -gt 0 ]; do
  case "$1" in
    -n|--name)
      if [ $# -lt 2 ]; then
        echo "error: $1 requires a value" >&2
        exit 1
      fi
      NAME="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [ -z "$NAME" ]; then
  echo "error: -n/--name is required" >&2
  usage >&2
  exit 1
fi

if [[ ! "$NAME" =~ ^[0-9]*$ ]]; then
  echo "error: test ID must contain only digits" >&2
  exit 1
fi
NAME="cli${NAME}"

# Single-quoted heredocs + __NAME__ avoid accidental expansion (e.g. awk '{print $1}'
# would otherwise pick up the writer function's $1).
substitute_name() {
  sed "s/__NAME__/${NAME}/g" >"$1"
}

write_json() {
  substitute_name "$1" <<'EMBED'
{
  "jobType": "ACCJob",
  "params": [
    {
      "reference": "TASK",
      "value": "assistJob"
    },
    {
      "reference": "workDir",
      "value": "__NAME___wdir"
    },
    {
      "reference": "SOFTWAREID",
      "value": "TESTSOFT"
    },
    {
      "reference": "inFile",
      "value": "../../__NAME__.sdf"
    },
    {
      "reference": "coordFile",
      "value": "__NAME__.xyz"
    },
    {
      "reference": "noJsonOutput",
      "value": "false"
    },
    {
      "reference": "situationsDBRoot",
      "value": "../../__NAME___KB"
    },
    {
      "reference": "assistedJob",
      "type": "JOB",
      "value":
      {
        "jobType": "CompChemJob",
        "directives": []
      }
    },
    {
      "reference": "runJob",
      "type": "JOB",
      "value":
      {
        "jobType": "ShellJob",
        "params": [
          {
            "reference": "CMD",
            "value": "bash ../../__NAME___fakeRunner.sh"
          },
          {
            "reference": "workDir",
            "value": "__NAME___wdir"
          }
        ]
      }
    },
    {
      "reference": "maxRestart",
      "value": "5"
    },
    {
      "reference": "VERBOSITY",
      "value": "4"
    }
  ]
}
EMBED
}

write_start_script() {
  substitute_name "$1" <<'EMBED'
"$javaDir/java" -jar "$ACCHome/target/autocompchem-$accVersion-jar-with-dependencies.jar" -j ../__NAME__.json  > __NAME__.log


EMBED
}

write_fake_runner() {
  substitute_name "$1" <<'EMBED'
#!/bin/bash
# This script fakes the execution of a job by copying files from previous runs (actual or simulated).

echo "Running fake job runner"
echo "pwd=$(pwd)"

rerunIdx=$(find . -name "__NAME__.out" | wc -l | awk '{print $1}')
cp -r ../../__NAME___out_tmpl_${rerunIdx}/* .

EMBED
}

write_check_script() {
  substitute_name "$1" <<'EMBED'
#!/bin/bash

function not_passed() {
  echo "NOT Passed: check condition leading to line '$1' of '$0'"
  exit -1
}

if [ ! -f __NAME__.log ] ; then not_passed $LINENO ; fi
if [ ! -d __NAME___wdir ] ; then not_passed $LINENO ; fi
if [ ! -f __NAME___wdir/__NAME__.out ] ; then not_passed $LINENO ; fi
if [ ! -f "__NAME___wdir/Job_#0.0_0/__NAME__.out" ] ; then not_passed $LINENO ; fi

n=0; n=$(grep -c -i "JobEvaluator: Situation perceived = TO_BE_DEFINED" __NAME__.log)
if [ 1 != "$n" ] ; then not_passed $LINENO ; fi

if ! grep -q -i "TO_BE_DEFINED" "__NAME___wdir/__NAME__.out" ; then not_passed $LINENO ; fi

n=0; n=$(grep -c -i "Termination status: 0" __NAME__.log)
if [ 1 == "$n" ] ; then echo Passed ; exit 0 ; fi
not_passed $LINENO
exit -1
EMBED
}

out_json="$SCRIPT_DIR/${NAME}.json"
out_start_script="$SCRIPT_DIR/${NAME}.sh"
out_check="$SCRIPT_DIR/${NAME}.check"
out_fake="$SCRIPT_DIR/${NAME}_fakeRunner.sh"
out_kb="$SCRIPT_DIR/${NAME}_KB/"
out_t0="$SCRIPT_DIR/${NAME}_out_tmpl_0/"
out_t1="$SCRIPT_DIR/${NAME}_out_tmpl_1/"

for p in "$out_json" "$out_start_script" "$out_check" "$out_fake" "$out_kb" "$out_t0" "$out_t1"; do
  if [ -e "$p" ]; then
    echo "error: already exists (change testID, or remove/rename existing files): $p" >&2
    exit 1
  fi
done

write_json "$out_json"
write_start_script "$out_start_script"
write_check_script "$out_check"
write_fake_runner "$out_fake"

chmod +x "$out_start_script" "$out_check" "$out_fake"

mkdir -p "$out_kb" "$out_t0" "$out_t1"

echo "Created:"
ls ${NAME}*
