server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: autocompchem-api
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: AutoCompChem REST API
    description: RESTful interface for computational chemistry automation
    version: 3.0.0
    contact:
      name: AutoCompChem Team
      url: https://github.com/denoptim-project/AutoCompChem 