package autocompchem.wiro.chem;

import java.util.Set;

import autocompchem.wiro.InputWriter;
import autocompchem.worker.Task;
import autocompchem.worker.Worker;

/**
 * This is a dummy class that is only used to provide a concrete implementation
 * of {@link ChemSoftInputWriter} that is agnostic to the software. This is
 * needed to print software-agnostic help messages from within this package,
 * hence knowing already that the unknown software is a computational chemistry 
 * software and that its input can be generated by an implementation of 
 * {@link ChemSoftInputWriter}. 
 * Effectively, it is a complex way to satisfy the machinery generating help
 * messages. Such machinery, in fact, required concrete implementations of
 * {@link Worker}, so the abstract class {@link ChemSoftInputWriter} cannot 
 * be used directly.
 * 
 * @author Marco Foscato
 */

public class AgnosticCompChemInputWriter extends InputWriter
{
    
//------------------------------------------------------------------------------

  	@Override
	public Set<Task> getCapabilities() {
  		return null;
	}

//------------------------------------------------------------------------------

	@Override
	public void performTask() {}
	
//------------------------------------------------------------------------------

	@Override
	public String getKnownInputDefinition() {
		return "inputdefinition/ChemSoftInputWriter.json";
	}

//-----------------------------------------------------------------------------
    
}
