# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
          
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build package
      # Runtime-dependent unit tests are too ofter unreproducible in GitHub 
      # runners, so they are explided from this CI workflow. See action #55 
      # (Commit 221eb14) for an example of a run that failed at those tests, 
      # but completed successfully upon simple re-run on GotHub runners.  
      run: mvn -B package --file pom.xml -Dtest="!autocompchem.run.SerialJobsRunnerTest,!autocompchem.run.ParallelJobsRunnerTest"
